-- 코드를 입력하세요
SELECT
    p.PRODUCT_CODE, SUM(p.PRICE * o.SALES_AMOUNT) AS SALES
FROM
    PRODUCT p
INNER JOIN OFFLINE_SALE o ON
    o.PRODUCT_ID = p.PRODUCT_ID
GROUP BY
    p.PRODUCT_ID
ORDER BY
    SALES DESC,
    p.PRODUCT_CODE ASC;